#!/bin/bash
# Prepares thumbnails for rotated images.
(
  grep 'include image.html .* rotation' ../_posts/*.md |
  sed -r 's/.*url="([^"]*)" rotation="([^"]*)".*/\2 \1/';
  grep 'include image.html' ../_posts/*.md |
  sed -r 's/.*url="([^"]*)".*/0 \1/';
) | while read ROTATION URL; do
  [[ -e thumbnails/"$URL" ]] &&
  printf 'Skipping %s.\n' "$URL" || {
    if [[ $ROTATION = 0 ]]; then
      convert "$URL" -scale 50% -quality 100% thumbnails/"$URL"
    else
      convert "$URL" -scale 50% -quality 100% -rotate $ROTATION  thumbnails/"$URL"
    fi && if [[ "${URL##*.}" = jpg ]]; then
      jpegoptim -m70 thumbnails/"$URL"
    elif [[ "${URL##*.}" = png ]]; then
      optipng -o7 thumbnails/"$URL"
    fi || exit 1
  }
done
